
[simulation]
simulation_rate = 1000.0

[initial]
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0]

[vehicle]

# Linear drag coefficient of the drone body
linear_damp = 0.1

# Angular drag coefficient of the drone body
angular_damp = 0.1

# Mass of the drone body
mass = 0.630

# Mass moment of inertia along principal axes
principal_inertia = [0.0012, 0.0012, 0.0012]

[[vehicle.motors]]
name = "back-right"
time_constant = 0.05
reverse = false
mass_moment = 0.02
normal = [0.0, 0.0, -1.0]
position = [-0.0825, +0.1125, 0.0]
motor_map = [10.452, 0.55]

[[vehicle.motors]]
name = "front-right"
time_constant = 0.05
reverse = true
mass_moment = 0.02
normal = [0.0, 0.0, -1.0]
position = [+0.0825, +0.1125, 0.0]
motor_map = [10.452, 0.55]

[[vehicle.motors]]
name = "back-left"
time_constant = 0.05
reverse = true
mass_moment = 0.02
normal = [0.0, 0.0, -1.0]
position = [-0.0825, -0.1125, 0.0]
motor_map = [10.452, 0.55]

[[vehicle.motors]]
name = "front-left"
time_constant = 0.05
reverse = false
mass_moment = 0.02
normal = [0.0, 0.0, -1.0]
position = [+0.0825, -0.1125, 0.0]
motor_map = [10.452, 0.55]

[acc_dist]

# Noise, bias and warp/scaling of sensor values
noise = [0.01, 0.01, 0.01]
bias = [0.0, 0.0, 0.0]
warp = [
    [1.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0],
]

# Cross-over frequency of the low-pass filter
lowpass_freq = 350.0

# 16 [G] * 9.81 [m/s^2/G] =>
max_range = 157.0

[gyr_dist]

# Noise, bias and warp/scaling of sensor values
noise = [0.001, 0.001, 0.001]
bias = [0.0, 0.0, 0.0]
warp = [
    [1.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0],
]

# Cross-over frequency of the low-pass filter
lowpass_freq = 350.0

# 2000 [deg/s] * 0.0174533 [rad/deg] =>
max_range = 34.91
